### ISSUE TITLE
Need to verify the checksum of downloaded crates

### ISSUE THREAD

**Issue by dupeiran001** [kellnr/kellnr#181] opened 2024-01-26 02:29 UTC
I found I keep getting `checksum failed` for the same crates when I have tried re-running the `cargo check`. And after deleting the cached package in kellnr, and download again, it works.

I suppose the checksum should be verified after [add_package](https://github.com/kellnr/kellnr/blob/e2ba195fc2a4512b184d47da46a1dab50501af91/crates/registry/src/cratesio_api.rs#L83) here, and re-download if it doesn't match the crates.io 's checksum.

**Comment by dupeiran001** [comment] 2024-01-30 01:16
more info: I found there's something wrong with the mem cache. It keep sending the wrong cksum package untile I restart the kellnr. Maybe the cksum need to be verified before store it in mem cache?

**Comment by secana** [comment] 2024-01-31 18:00
Can you verify if the problem still exists if you disable the mem cache? You can do that by setting it's size to 0. That would help me pin down if the issue is in the mem cache or already before that.

**Comment by dupeiran001** [comment] 2024-02-01 00:17
Yes, set size to zero solves the problem.

**Comment by secana** [comment] 2024-02-03 18:30
Thank you for verifying. I'll have a look what is wrong with the cacheing logic.

**Comment by Christiaan676** [comment] 2024-02-16 13:17
Reading the issue, I don' t think that there is anything wrong with the cashing logic. Downloading of crate went wrong, resulting in a broken file on disk. When the package is requested by cargo, the file is loaded from disk and cached. Resulting in the checksum error.

Removing the file from disk will not remove the file from the cache. So the next download will return the cached version, and will again result in a checksum error. Restarting Kellnr solves this, as it will clear the memory file cache, resulting in a redownload of the crate the next time it is requested.

**Comment by secana** [comment] 2024-03-06 20:56
There is now checksum that can be checked as crates.io does not provide any. I'll close the issue until there is more information available. Reproducing the issue is still not possible.

**Closed by secana** 2024-03-06 20:56 UTC
Labels: bug
