### ISSUE TITLE
failed to download replaced source registry `crates-io`  Caused by: failed to verify the checksum of `bitflags v1.3.2 (registry `kellnr-cratesio`)`

### ISSUE THREAD

**Issue by adrianncovaci** [kellnr/kellnr#169] opened 2024-01-11 09:22 UTC
I have a droplet setup and Im running kellnr in order to cache crates on that server so that I dont have to refetch them afterwads for other projects. 
This container is running on my remote server:
```bash
docker run --rm -it     -p 8000:8000     -e "KELLNR_ORIGIN__HOSTNAME=hostip"     -e "KELLNR_SETUP__ADMIN_TOKEN=my_super_secret_auth_key"     -e "KELLNR_PROXY__ENABLED=true"     -v $(pwd):/opt/kdata ghcr.io/kellnr/kellnr:5.0.0
```
and this is my `.cargo/toml` file:
```toml
[source.crates-io]
replace-with = "kellnr-cratesio"
[source.kellnr-cratesio]
registry = "sparse+http://hostip:8000/api/v1/cratesio/"
```
When I build the project, I get:
 ```
 error: failed to download replaced source registry `crates-io`
Caused by:
  failed to verify the checksum of `bitflags v1.3.2 (registry `kellnr-cratesio`)`
```
It is properly caching crates from crates.io, since the `crates/` directory gets populated (but fails when downloading the `bitflags` crate). I've also checked with other projects as well and it fails with other crates as well (not necessarily `bitflags`).

**Comment by secana** [comment] 2024-01-13 11:23
One possible problem could be that the crates where downloaded before from crates.io and now they are downloaded from your kellnr proxy. Unfortunately cargo is not able to work with "mixed" indicies.

Can you try to delete your `Cargo.lock` and clean your old index cache with `rm -rf ~/.cargo/registry/*` and check if the issue persists?

**Comment by adrianncovaci** [comment] 2024-01-13 11:42
> One possible problem could be that the crates where downloaded before from crates.io and now they are downloaded from your kellnr proxy. Unfortunately cargo is not able to work with "mixed" indicies.
> 
> 
> 
> Can you try to delete your `Cargo.lock` and clean your old index cache with `rm -rf ~/.cargo/registry/*` and check if the issue persists?

Sorry, I forgot to mention, the issue persists even after deleting the registry directory and running 'cargo clean'

**Comment by secana** [comment] 2024-01-14 14:39
If if it's not a mixed index, I don't have another idea, but I'll try to help debug the issue.

Can you provide logs from Kellnr (log level = trace) and from cargo when you run it with a verbose flag? Maybe there is a hint somewhere in the logs.

**Comment by adrianncovaci** [comment] 2024-01-14 16:41
when running with trace kellnr log level I get:
`2024-01-14T16:35:21.846510Z TRACE registry::cratesio_api: Crate found in cache, skipping download`.

`cargo run --verbose`
 doesn't return any other errors than:
 ```error
  Downloaded unicase v2.7.0 (registry `kellnr-cratesio`)
error: failed to download replaced source registry `crates-io`

Caused by:
  failed to verify the checksum of `unicase v2.7.0 (registry `kellnr-cratesio`)`

 ```
I've removed ~/.cargo/registry
I've ran `cargo clean`
I've deleted `Cargo.lock`

**Comment by secana** [comment] 2024-01-21 14:14
I'm out of ideas, as I cannot reproduce the issue. I'll close the issue, but if you find out what the issue is, or have more information available, feel free to reopen it.

**Closed by secana** 2024-01-21 14:14 UTC
